#!/usr/bin/env bash

status="$(cat /tmp/inhibit-status)"

if [ $status ]; then
    echo '<span color="gray" font="FontAwesome"> Off</span>'
    rm /tmp/inhibit-status
else
    echo '<span color="white" font="FontAwesome"> On</span>'
    echo "True" >> /tmp/inhibit-status
fi
