#!/usr/bin/env bash
#

#A script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
echo -e "$current_profile"

case $BLOCK_BUTTON in 
    1) ~/.config/i3/scripts/power-profiles;;
esac
